package uk.co.awe.analyses;

import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;

/**
 * A configuration panel which can be used to set the maximum order of the
 * polynomial regression.
 * 
 * @author AWE Plc
 */
public class PolynomialRegressionPanel extends JPanel {

    private static final int START_NUMBER = 2;
    private static final int MAX_NUMBER = 9;
    private static final int MIN_NUMBER = 1;
    private static final int STEP_SIZE = 1;
    
    private final PolynomialRegression polynomialRegression;

    /**
     * Creates new form PolynomialRegressionPanel.
     * 
     * @param polynomialRegression The polynomal regression analysis method to
     * which this panel is associated
     */
    public PolynomialRegressionPanel(PolynomialRegression polynomialRegression) {
        initComponents();
        
        this.polynomialRegression = polynomialRegression;
        this.orderSpinner.setModel(new SpinnerNumberModel(
                START_NUMBER, MIN_NUMBER, MAX_NUMBER, STEP_SIZE));
        this.orderSpinner.getModel()
                .addChangeListener(this.polynomialRegression);
    }

    /**
     * Return the order set by the panel.
     * 
     * @return The order currently set on the panel
     */
    int getOrder() {
        return (Integer) this.orderSpinner.getValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderLabel = new javax.swing.JLabel();
        orderSpinner = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        setLayout(new java.awt.GridLayout(1, 0));

        orderLabel.setText("Order");
        add(orderLabel);
        add(orderSpinner);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel orderLabel;
    private javax.swing.JSpinner orderSpinner;
    // End of variables declaration//GEN-END:variables

}
